### ISSUE TITLE
Add release pipelines to Jenkins

### ISSUE THREAD

**Issue by blankdots** [ATTX-project/development-environment#14]
#### Description
New pipelines that use master branch and release parameter must be added to Jenkins
#### DoD
There are new pipelines for every artifact
#### Testing
Peer review

**Comment by jkesanie** [comment]
I've created a service account under attxprojectpusher in Docker Hub and given it write access to all the relevant repositories. 

I've deleted all images with "latest" tag, so deployment configurations must be updated to reflect that change.

**Comment by joasilva** [comment]
Now that this task is done, we should follow-up with updating the docker-compose.yml files: https://github.com/ATTX-project/project-management/issues/94
