### ISSUE TITLE
DevOps: Automatic github release

### ISSUE THREAD

**Issue by jkesanie** [ATTX-project/development-environment#17]
#### Description

When pull-request is merged to master, Jenkins pipeline triggers automatic release to Github.

#### DoD

Working pipeline(s)

#### Testing

Peer-review

**Comment by blankdots** [comment]
Pipelines seem restored and a new issue was detected as nodejs is not configured: https://github.com/ATTX-project/development-environment/issues/19
We might need to have a issue for better configuring Archiva not to run into the same password expiring problems.

**Comment by blankdots** [comment]
We need status update on request for making Jenkins server accessible from github.
