### ISSUE TITLE
ELAG2017: setup demo images

### ISSUE THREAD

**Issue by jkesanie** [ATTX-project/development-environment#18]
#### Description
Setup any required images for ELAG demo.

#### DoD

Required images prepared and configuration ready.

#### Testing
Peer-review

**Comment by blankdots** [comment]
Images set up:

- [x] attxproject/demodata:elag2017
- [x] attxproject/attx-fuseki::elag2017
- [x] attxproject/gm-api:1.1
- [x] attxproject/uv-attx-dpus:elag2017
