### ISSUE TITLE
Configure proxy-connectors for Archiva 

### ISSUE THREAD

**Issue by joasilva** [ATTX-project/development-environment#20]
#### Description
We need our own local copies of artifacts. This requires two things:
* Projects must use archiva as the main source for all artifacts
* Archiva must be configured to work as a proxy for all artifact repositories

#### DoD
* Configure archiva
* Change repository configuration for all the projects

#### Testing
Working Jenkins pipelines

**Comment by blankdots** [comment]
Reading:
https://archiva.apache.org/docs/1.3.6/adminguide/proxy-connectors.html
