### ISSUE TITLE
Document Jenkins/Github flow from pull-request to deployed artifacts

### ISSUE THREAD

**Issue by jkesanie** [ATTX-project/development-environment#22]
Description

Issue focuses on pipelines and code that is used to create artifacts such as jars and tars (not the images!). Create a diagram and documentation that shows interactions between Jenkings and Github starting from a pull request and ending with the new version of the the artifact being deployed to Archiva.

DoD

Wiki documentation.

Testing

Peer-review

**Comment by blankdots** [comment]
There are two types of flows:
1. /feature-* branch to /dev branch
2. /dev branch to /master branch

Either one can be solved with Gradle plugins or github hooks

The image below describes the build and deploy workflow from a /feature-* branch to /dev branch.

![build_workflow](https://user-images.githubusercontent.com/47524/28774958-5fb1989a-75f8-11e7-9d2f-8473f7af8ee9.png)
--------------------------------
The image below describes the build and deploy workflow from a /dev branch to /master branch.
![branch_workflow_master](https://user-images.githubusercontent.com/47524/28775263-b5c1c894-75f9-11e7-8249-6def957d031a.png)

**Comment by blankdots** [comment]
Pull request Tutorial with githooks:
http://www.inanzzz.com/index.php/post/ljgv/setup-github-and-jenkins-integration-for-pull-request-builder-and-merger

Documentation from the actual plugin with examples from Jenkins DSL: https://github.com/janinko/ghprb

**Comment by jkesanie** [comment]
@blankdots could you add these images also to the io.pages images folder.

**Comment by blankdots** [comment]
@jkesanie done.
