### ISSUE TITLE
Update PyPi Ivy repository with new version

### ISSUE THREAD

**Issue by blankdots** [ATTX-project/development-environment#4]
#### Description
A new version of the PyPi Ivy repository for PyGradle has been developed at: https://github.com/blankdots/ivy-pypi-repo and with a docker image in https://github.com/ATTX-project/development-environment/tree/dev/pivy-repo
#### DoD
- [x] The new version is running in the attx dev environment
- [x] Existing Python Gradle builds use the new repository 
#### Testing
Peer review

**Comment by joasilva** [comment]
Docker image build and pushed to: https://hub.docker.com/r/attxproject/pypirepo/
