### ISSUE TITLE
Update the Dockerfile for attx-jenkins

### ISSUE THREAD

**Issue by joasilva** [ATTX-project/development-environment#5]
#### Description
Update the Dockerfile for attx-jenkins:
- apt-get install apt-utils
- apt-get clean at the end
#### DoD
Dev tools and libraries such as gcc should be invoked from BASH in the container
#### Testing
_How one would test that the things/artifacts have been achieved. Options (Peer review, Unit Test, BDD testing, Integration Test)._

**Comment by blankdots** [comment]
Looks like this might work:
```
FROM jenkins

MAINTAINER João M. da Silva <joao.silva@helsinki.fi>

USER root
RUN apt-get update \
      && apt-get install -y sudo \
      && apt-get install -y libxml2-dev libxslt1-dev python-dev \
      && apt-get install -y build-essential \
      && apt-get install -y zlib1g-dev

RUN echo "jenkins ALL=NOPASSWD: ALL" >> /etc/sudoers

```

**Comment by jkesanie** [comment]
Image should also contain Maven

**Comment by joasilva** [comment]
Commit diff: https://github.com/ATTX-project/development-environment/commit/b36370857882621957308ab8e6cb696e8a36bac6
