### ISSUE TITLE
docker compose for Dev Environment

### ISSUE THREAD

**Issue by blankdots** [ATTX-project/development-environment#6]
#### Description
create a new docker-compose for Dev environment for new attx jenkins #5 and pypi repo #4 
#### DoD
Docker compose file for dev stack in repository and on the server.
Create docker-compose or dev environment:
* CI e.g. Jenkins
* push new container should be pushed to Docker Hub
* Test configuration
Builds run again.
#### Testing
Peer review

**Comment by blankdots** [comment]
@joasilva said:
The docker-compose stack should launch attx-jenkins with the following options:

`/usr/bin/docker run --link picy_repo:pivyrepo -d -v /var/run/docker.sock:/var/run/docker.sock -v $(which docker):/usr/bin/docker -p 49001:8080 -v /data/jenkins:/var/jenkins_home -t attxproject/attx-jenkins:latest`

**Comment by joasilva** [comment]
First version of the docker-compose.yml file: https://github.com/ATTX-project/development-environment/blob/feature-attx-jenkins/docker-compose.yml
