### ISSUE TITLE
HTTP Mock library for unit testing

### ISSUE THREAD

**Issue by jkesanie** [ATTX-project/development-environment#8]
#### Description
We should have a common library that can be used to provide simple mocks for http endpoints of different platform components. We could use some existing HTTP mocking component as the basis for implementation and just add ready made "mappings" for services that we use.

Requirements:
- APIs to mock: fuseki, es, wf-api, gm-api, uv

#### DoD
Use http mocking in wf-api and gm-api projects.

#### Testing
Unit tests

**Comment by blankdots** [comment]
GM-API mocking has been done using: https://docs.python.org/dev/library/unittest.mock.html, http://httpretty.readthedocs.io/en/latest/ and sqlite3
Other options: 
* https://pypi.python.org/pypi/requests-mock
* https://pypi.python.org/pypi/httmock/
* https://pypi.python.org/pypi/pytest-mock

for WF-API there is a need to mock the MySQL connection. One could use:
* https://pypi.python.org/pypi/testing.mysqld (tested without success)
* gradle task which starts, inserts fixtures (needed) and shuts downs a container with mysql
* test if sqlite could be used for testing with the needed test fixtures from MySQL

**Comment by blankdots** [comment]
@jkesanie I think this can be closed - we already know how to mock responses and endpoints in Python and gm-api tests is a proof of that, However for WF-API I do not think mocking MariaDB should be a part of the unit tests, but the functionality should be tested in Integration tests.
