### ISSUE TITLE
Setup artifact repository as part of the development environment

### ISSUE THREAD

**Issue by jkesanie** [ATTX-project/development-environment#9]
#### Description
We need an actual artifact repository to support integration tests. 
#### DoD
Artifact repository (which one?) configured as part of the development environment containers.
#### Testing
Peer-review

**Comment by jkesanie** [comment]
https://hub.docker.com/r/xetusoss/archiva/

**Comment by blankdots** [comment]
Some possibly useful resources:
* http://stackoverflow.com/questions/27676838/how-to-publish-aar-file-to-apache-archiva-with-gradle
* http://evertrue.github.io/blog/2014/07/21/setting-up-an-archiva-repository/ - Setting Up an Archiva Repository and Deploying Artifacts with Jenkins
* http://tiemensfamily.com/TimOnCS/2014/04/16/gradle-with-local-archiva/
* Installing and configuring Archiva: https://docs.oracle.com/middleware/1213/core/MAVEN/populating_archiva.htm#MAVEN8843

According to this: https://binary-repositories-comparison.github.io/ JFrog seems to be more complete in features and support for different languages (but with Pro version)

**Comment by jkesanie** [comment]
@joasilva: Remove static docker-compose.yml and then this is fine.
